### ISSUE TITLE
Metadata update failure

### ISSUE THREAD

**Issue by jeffreyherzog** [pyr-opendatafr/R-Insee-Data#1]
Hi -- I get a 500 error when updating metdata using the INSEE package. Is there a fix for this? Thanks

Warning messages:
1: In utils::download.file(file_to_dwn, temp_file, mode = insee_download_option_idbank_list,  :
  cannot open URL 'https://www.insee.fr/en/statistiques/fichier/2868055/202108_correspondance_idbank_dimension.zip': HTTP status was '500 '
2: In utils::download.file(file_to_dwn, temp_file, mode = insee_download_option_idbank_list,  :
  cannot open URL 'https://www.insee.fr/en/statistiques/fichier/2868055/202108_correspondance_idbank_dimension.zip': HTTP status was '500 '
3: In get_idbank_list(c("CLIMAT-AFFAIRES", "ENQ-CONJ-SERV", "ENQ-CONJ-MENAGES",  :
  

Idbank list download failed 
Package's internal data has been used instead 
Please contact the package maintainer if this error persists

**Comment by hadrilec** [comment]
Hi @jeffreyherzog, thank you very much for this feedback. The latest version of the package available on GitHub is a fix.
You can get it with the following command.
`devtools::install_github("pyr-opendatafr/R-Insee-Data")`
I will update in the coming days the CRAN version.
Best regards,
Hadrien

**Comment by jeffreyherzog** [comment]
Hi Hadrien -- Thank you very much for your help! Your package is
very useful. Best, Jeff

**Comment by hadrilec** [comment]
package version 1.1.3 available on CRAN is a fix
