### ISSUE TITLE
Disponibilité projections démographiques et pyramide des âges 

### ISSUE THREAD

**Issue by pvanborre** [pyr-opendatafr/R-Insee-Data#7]
Bonjour Hadrien,
Déjà je voulais te remercier pour ce package que j'utilise actuellement en tant que stagiaire au bureau retraites de la DREES pour éviter de retélécharger des Excel chaque année.

Dans ce cadre j'aimerais utiliser POPULATION-STRUCTURE pour obtenir la pyramide des âges, malheureusement il n'y a à ma connaissance que des données de populations par tranche d'âge dans le package et non âge par âge.
J'aimerais en fait pouvoir "récupérer" le fichier Excel demoInsee (où année par année, âge par âge, sexe par sexe, il y a les effectifs de population) téléchargeable à cette adresse : https://www.insee.fr/fr/outil-interactif/5014911/pyramide.htm
Est ce que tu sais s'il serait faisable d'ajouter cette pyramide des âges au package, ou s'il n'est pas vraiment prévu de l'ajouter ?

De la même manière j'aimerais disposer des projections démographiques 2021-2070, avec les différents scénarios, est ce que tu penses que cela pourrait être faisable dans le package ?

Bonne soirée !
Paul

**Comment by hadrilec** [comment]
Bonjour Paul,

le package R insee a pour objectif de faciliter l'usage de l'API BDM, donc son objectif n'est pas de manipuler les fichiers excel ou csv publies par l'insee.

Par contre, le package python pynsee contient des fonctions qui permettent de faciliter le téléchargement et la manipulation de certains fichiers disponibles sur insee.fr.
Je te conseille d'aller voir la documentation du package:
https://pynsee.readthedocs.io/en/latest/search_data.html#search-files-on-insee-fr

Ci dessous un exemple que j'ai fait rapidement, qui montre comment utiliser les fichiers du recensement de 2016 pour obtenir une pyramide des ages. Il faut cependant verifier que tout est bien correct, mais cela pourrait etre un bon point de depart.


```python
from pynsee import *
import pandas as pd
import matplotlib.pyplot as plt

# liste des fichiers disponibles
files = get_file_list()
files[files.collection.str.contains('^RP')]

# description des colonnes du fichier RP
metacol = get_column_metadata("RP_INDCVI_2016")
metacol

# telechargement des donnees
age = download_file('RP_INDCVI_2016')

# calcul des statistiques agregees
age2 = (age[['AGED', 'SEXE', 'IPONDI']]
        .assign(AGED = lambda x: pd.to_numeric(x['AGED']))
        .assign(IPONDI = lambda x: pd.to_numeric(x['IPONDI']))
        .groupby(['SEXE', 'AGED'])['IPONDI']
        .agg('sum')
        .reset_index(drop=False))

# construction du graphique
male =  age2[age2['SEXE'] == '1']
female =  age2[age2['SEXE'] == '2']

y_male = male['AGED']
x_male = male['IPONDI']

y_female = female['AGED']
x_female = female['IPONDI']

fig, axes = plt.subplots(ncols=2, sharey=True, figsize=(12, 5))
fig.suptitle("Population Pyramid in France in 2016", fontweight='bold')
fig.tight_layout(pad = 2)

#define male and female bars
axes[0].barh(y_male, x_male, align='center', color='blue')
axes[0].set(title='Males')
axes[1].barh(y_female, x_female, align='center', color='red')
axes[1].set(title='Females')
axes[0].invert_xaxis()
```

![pop_pyramid_fr](https://github.com/pyr-opendatafr/R-Insee-Data/assets/66560093/4bcc092d-71e5-4b75-b241-1064c6255b82)

**Comment by pvanborre** [comment]
Bonjour Hadrien,

**Comment by pvanborre** [comment]
Bonjour Hadrien,

Merci beaucoup pour ta réponse.
Effectivement très bonne idée de passer sur Python : la pyramide des âges que ton code fournit est exactement ce que je recherchais...

Petite remarque de mémoire : ce code ne marche pas dans un container Docker (avec une erreur de mémoire),
alors qu'il fonctionne lorsqu'on le fait tourner directement avec le Python de ma machine.
Tu sembles a priori déjà avoir rencontré ce problème sur un autre dataset : https://github.com/InseeFrLab/pynsee/commit/106bd44c2e02f316e20bbbcbdc5228478bf5fcb0
Je me suis donc permis de sélectionner uniquement les variables d'intérêt dans le code pour que cela consomme moins de mémoire
```
age = download_file('RP_INDCVI_2016', variables = ['AGED', 'SEXE', 'IPONDI'])
``` 

Merci encore et bonne soirée,
Paul
